# -*- coding: utf-8 -*-
"""AI LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYIQfC2kXIJAdvYb-aiOzPsB4oPtLoTV
"""

A=5;B=6;
c=A+B;
print("sum=",c);

d=A-B;
print("subtraction=",d);

e=A*B;
print("multiplication=",e);

f=A/B;
print("division=",f);